spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/rancher_test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: classact!
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
